#!/bin/sh

# cd front-end && \

# echo "=============================" && \
# echo "=       Linting Files       =" && \
# echo "=============================" && \
# npm run lint && \


# echo "=============================" && \
# echo "=       Running Tests       =" && \
# echo "=============================" && \
# npm test -- --watchAll=false --coverage
